### ISSUE TITLE
value error

### ISSUE THREAD

**Issue by xiuliren** [JuliaEditorSupport/deoplete-julia#10]
I am using this from SpaceVim with Julia layer. The `deoplete-julia` is already the same with current master.
My current Julia version is 0.6.

![image](https://user-images.githubusercontent.com/7651573/41558643-6deb4d42-730f-11e8-855f-f182508b4a21.png)

It seems that this is caused from this line:
https://github.com/JuliaEditorSupport/deoplete-julia/blob/master/rplugin/python3/deoplete/sources/julia.py#L28

**Comment by oxinabox** [comment]
Hi,
See the depreciation notice in the readme. This plugin only supports julia 0.5.
While 0.6 wouldn't be too hard to do,
0.6 supports the LSP which is generally better.
If I had time to work on this, i'ld be spending it on LSP instead,

**Comment by xiuliren** [comment]
I have created a PR to fix this in SpaceVim
https://github.com/SpaceVim/SpaceVim/pull/1850
