### ISSUE TITLE
Popup error 

### ISSUE THREAD

**Issue by elsuizo** [JuliaEditorSupport/deoplete-julia#4]
Hi first thanks for this. I got an error popup like this. 
I got the last neovim. The completion works fine exept for this error.
![error_nvim_julia](https://cloud.githubusercontent.com/assets/3966561/18816637/46f2e218-8324-11e6-9254-b5d35332a681.png)

**Comment by ararslan** [comment]
I get the same thing, except nothing at all works for me--I only get the error.

**Comment by oxinabox** [comment]
Fixed.
It was a typo in code path that was not exercised in the older version of deoplete that I was testing on (I updated and could reproduce).

Thanks for raising the issue.

**Comment by ararslan** [comment]
As an aside, @oxinabox you could transfer ownership of this repo to the organization rather than maintaining a fork here. Or you could contact GitHub support and they'll separate this into its own repo so it's no longer a fork. Just a thought.

**Comment by oxinabox** [comment]
> Or you could contact GitHub support and they'll separate this into its own repo so it's no longer a fork. Just a thought.

@ararslan funny you should mention that, I just clicked send on a support request to do just that when I saw your notification.
I will probably take hours-days, from what I hear.

**Comment by oxinabox** [comment]
@ararslan , @elsuizo  is this working fine now?

**Comment by ararslan** [comment]
Yes, I no longer get that error

**Comment by elsuizo** [comment]
Yeah super great man, thanks !!!
